apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arkgame-pv-claim
spec:
  accessModes: {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}